apiVersion: apps/v1
kind: Deployment
metadata:
  name: canaryapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yellow
      version: v2.0
  template:
    metadata:
      labels:
        app: yellow
        version: v2.0
    spec:
      containers:
      - name: container01
        image: hashicorp/http-echo:alpine
        args:
        - '-text="Welcome to the Canary App (1.0)!"'
