apiVersion: batch/v1
kind: CronJob
metadata:
    name: echocomplete
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
     spec:
        parallelism: 5
        completions: 20 
        template:
          spec:
            containers:
            - name: echo
              image: centos:7
              command: ["echo", "This text here means success!"]
            restartPolicy: Never

