apiVersion: apps/v1
kind: Deployment
metadata:
  name: existingapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: yellow
      version: v1.0
  template:
    metadata:
      labels:
        app: yellow
        version: v1.0
    spec:
      containers:
      - name: container01
        image: hashicorp/http-echo:alpine
        args:
        - '-text="Welcome to the Existing App (1.0)!"'
