apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image:  busybox:1.34.0
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
  initContainers:   # init containers are "opening acts", they MUST run BEFORE "containers" are launched!
  - name: init-myservice
    image:  busybox:1.34.0
    command: ['sh', '-c', 'until nslookup myservice; do echo waiting for myservice; sleep 2; done;']
  - name: init-mydb
    image:  busybox:1.34.0
    command: ['sh', '-c', 'until nslookup mydb; do echo waiting for mydb; sleep 2; done;']
